// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}
declare module "*.gif" {
  /**
   * A path to the GIF file
   */
  const path: `${string}.gif`;
  export = path;
}
declare module "*.webp" {
  /**
   * A path to the WEBP file
   * (used for the Annoying Dog image, which is a GIF converted to WEBP for better performance)
   */
  const path: `${string}.webp`;
  export = path;
}
declare module "*.ogg" {
  /**
   * A path to the OGG audio file
   */
  const path: `${string}.ogg`;
  export = path;
}

declare module "*.wav" {
  /**
   * A path to the WAV audio file
   */
  const path: `${string}.wav`;
  export = path;
}

declare module "*.png" {
  /**
   * A path to the PNG file
   */
  const path: `${string}.png`;
  export = path;
}


declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
